### ISSUE TITLE
NullPointerExpection when user doesn't have any notifications

### ISSUE THREAD

**Issue by andy1024** [andy1024/eledger-parser#6]
DEBUG [main] (Application.java:53) - Event fired: app.event.afterSingleUserLogout
Exception in thread "main" java.lang.NullPointerException
	at org.warheim.eledger.parser.EntryPoint.run(EntryPoint.java:110)
	at org.warheim.eledger.parser.EntryPoint.main(EntryPoint.java:41)

**Comment by andy1024** [comment]
Fixed.
