### ISSUE TITLE
Authorization fails when using Jsoup provider 

### ISSUE THREAD

**Issue by andy1024** [andy1024/eledger-parser#7]
WARN [main] (WebCall.java:42) - Expected status 302 got 200
Exception in thread "main" org.warheim.net.WrongStatusException: Expected 302, got 200 exitting
	at org.warheim.net.WebCall.doCall(WebCall.java:43)
	at org.warheim.eledger.web.HttpReqRespHandler.getAllData(HttpReqRespHandler.java:65)
	at org.warheim.eledger.parser.EntryPoint.run(EntryPoint.java:88)
	at org.warheim.eledger.parser.EntryPoint.main(EntryPoint.java:42)

**Comment by andy1024** [comment]
Jsoup appears to handle things a bit differently than apache. Server returns 200 instead of 302 while authorization.
Fixed along with issue #8
